# Generated by Django 5.2.5 on 2025-11-09 11:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Service Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('duration_days', models.IntegerField(default=30, verbose_name='Duration (days)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('lead', 'Lead'), ('client', 'Client'), ('partner', 'Partner')], default='lead', max_length=10, verbose_name='Status')),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='Company')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Position')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('email', 'phone')},
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Deal Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Deal Amount')),
                ('probability', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Probability (%)')),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('won', 'Won'), ('lost', 'Lost'), ('on_hold', 'On Hold')], default='new', max_length=20, verbose_name='Status')),
                ('expected_close_date', models.DateField(blank=True, null=True, verbose_name='Expected Close Date')),
                ('actual_close_date', models.DateField(blank=True, null=True, verbose_name='Actual Close Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='contacts.contact', verbose_name='Contact')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='contacts.service', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Deal',
                'verbose_name_plural': 'Deals',
                'ordering': ['-created_at'],
            },
        ),
    ]
