# Generated by Django 5.2.7 on 2026-03-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditTrail",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("actor", models.CharField(blank=True, default="", max_length=255)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("contact_created", "Contact created"),
                            ("contact_updated", "Contact updated"),
                            ("contact_deleted", "Contact deleted"),
                            ("deal_created", "Deal created"),
                            ("deal_status_changed", "Deal status changed"),
                        ],
                        max_length=64,
                    ),
                ),
                ("entity_type", models.CharField(max_length=64)),
                ("entity_id", models.IntegerField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["-created_at"]},
        ),
    ]
