# Generated by GPT-5.4 on 2026-04-01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0002_audittrail"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="inn",
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.CreateModel(
            name="ContactCompanyDetails",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("company_name", models.CharField(blank=True, default="Не найдено", max_length=500)),
                ("inn", models.CharField(blank=True, default="Не найдено", max_length=12)),
                ("kpp", models.CharField(blank=True, default="Не найдено", max_length=20)),
                ("ogrn", models.CharField(blank=True, default="Не найдено", max_length=20)),
                ("status_text", models.CharField(blank=True, default="Не найдено", max_length=255)),
                ("address", models.TextField(blank=True, default="Не найдено")),
                ("okved", models.CharField(blank=True, default="Не найдено", max_length=500)),
                ("director", models.CharField(blank=True, default="Не найдено", max_length=255)),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contact",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_details",
                        to="contacts.contact",
                    ),
                ),
            ],
            options={
                "verbose_name": "Дополнительные данные компании",
                "verbose_name_plural": "Дополнительные данные компаний",
                "ordering": ["-updated_at"],
            },
        ),
    ]
