# Generated by Django 5.2.7 on 2026-03-12 08:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=500, verbose_name='Тема письма')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата получения')),
                ('text', models.TextField(verbose_name='Текст письма')),
                ('sender_email', models.EmailField(blank=True, max_length=255, verbose_name='Email отправителя')),
                ('message_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ID письма')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-date'],
            },
        ),
    ]
