# Generated by Django 5.2.5 on 2026-02-11 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('purpose', models.CharField(choices=[('register', 'Registration verification'), ('reset', 'Password reset')], db_index=True, max_length=20)),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('used', models.BooleanField(db_index=True, default=False)),
                ('attempts', models.PositiveIntegerField(default=0)),
            ],
            options={
                'indexes': [models.Index(fields=['email', 'purpose', 'used'], name='authenticat_email_4e5e6b_idx'), models.Index(fields=['expires_at'], name='authenticat_expires_3b0348_idx')],
            },
        ),
    ]
