tunnel: ИМЯ_ТУННЕЛЯ
credentials-file: путь_к_credentials.json

ingress:
  - hostname: ваш-домен.serv00.net
    service: http://localhost:8012
  - service: http_status:404

# Добавьте эту секцию для авторизации через токен
# Но лучше использовать login сначала