# """
# Django settings for config project.

# Generated by 'django-admin startproject' using Django 5.2.7.

# For more information on this file, see
# https://docs.djangoproject.com/en/5.2/topics/settings/

# For the full list of settings and their values, see
# https://docs.djangoproject.com/en/5.2/ref/settings/
# """

# from pathlib import Path

# # Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent


# # Quick-start development settings - unsuitable for production
# # See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# # SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-o4uujwhpfz6248wv%@phh$a++xc1m30uzxrqx%ol(5#5op8id)'

# # SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True

# ALLOWED_HOSTS = []


# # Application definition

# INSTALLED_APPS = [
#     'django.contrib.admin',
#     'django.contrib.auth',
#     'django.contrib.contenttypes',
#     'django.contrib.sessions',
#     'django.contrib.messages',
#     'django.contrib.staticfiles',
# ]

# MIDDLEWARE = [
#     'django.middleware.security.SecurityMiddleware',
#     'django.contrib.sessions.middleware.SessionMiddleware',
#     'django.middleware.common.CommonMiddleware',
#     'django.middleware.csrf.CsrfViewMiddleware',
#     'django.contrib.auth.middleware.AuthenticationMiddleware',
#     'django.contrib.messages.middleware.MessageMiddleware',
#     'django.middleware.clickjacking.XFrameOptionsMiddleware',
# ]

# ROOT_URLCONF = 'config.urls'

# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         'DIRS': [],
#         'APP_DIRS': True,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#             ],
#         },
#     },
# ]

# WSGI_APPLICATION = 'config.wsgi.application'


# # Database
# # https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


# # Password validation
# # https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]


# # Internationalization
# # https://docs.djangoproject.com/en/5.2/topics/i18n/

# LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC'

# USE_I18N = True

# USE_TZ = True


# # Static files (CSS, JavaScript, Images)
# # https://docs.djangoproject.com/en/5.2/howto/static-files/

# STATIC_URL = 'static/'

# # Default primary key field type
# # https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

# DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
 

# DEFAULT_AUTOfrom pathlib import Path
from datetime import timedelta
from decouple import config  # ← pip install python-decouple
import os 
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent
# SECRET_KEY = 'django-insecure-7j#3(d%=j8h(0bx9-louse(gc-ne57)dv8&l*at_9@#hh7m^=t'

# SECRET_KEY = config('SECRET_KEY', default='super-secret-jwt-key-1234567890')
SECRET_KEY = 'django-insecure-j4qv2$-!q_yfd0n&*qt^n1#mya66nqah9r3b1m1@-s!$s0pe$2'

YOOKASSA_SHOP_ID = '1335151'
YOOKASSA_SECRET_KEY = 'test_3RDrQQ3KHo_QzYn9jw0orffJb1u8ILESiNzOfuIyi4I'

CONTACT_SERVICE_URL = os.getenv('CONTACT_SERVICE_URL', 'http://127.0.0.1:8005')
PUBLIC_PAYMENTS_BASE_URL = os.getenv('PUBLIC_PAYMENTS_BASE_URL', 'https://incessantly-golden-gannet.cloudpub.ru')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'no-reply@crm.local')

ONEC_BASE_URL = os.getenv('ONEC_BASE_URL', 'http://host.docker.internal/1c/odata/standard.odata/')
ONEC_ODATA_BASE_URL = os.getenv('ONEC_ODATA_BASE_URL', ONEC_BASE_URL)
ONEC_CREATE_INVOICE_URL = os.getenv('ONEC_CREATE_INVOICE_URL', ONEC_ODATA_BASE_URL)
ONEC_MARK_PAID_URL = os.getenv('ONEC_MARK_PAID_URL', ONEC_ODATA_BASE_URL)
ONEC_USERNAME = os.getenv('ONEC_USERNAME', '')
ONEC_PASSWORD = os.getenv('ONEC_PASSWORD', '')
ONEC_TIMEOUT_SECONDS = int(os.getenv('ONEC_TIMEOUT_SECONDS', '20'))
ONEC_TRANSPORT_MODE = os.getenv('ONEC_TRANSPORT_MODE', 'bridge')
ONEC_BRIDGE_URL = os.getenv('ONEC_BRIDGE_URL', 'http://127.0.0.1:8013/invoke')
ONEC_BRIDGE_SECRET = os.getenv('ONEC_BRIDGE_SECRET', '')
ONEC_BRIDGE_TIMEOUT_SECONDS = int(os.getenv('ONEC_BRIDGE_TIMEOUT_SECONDS', '60'))
ONEC_RESTART_EACH_REQUEST = os.getenv('ONEC_RESTART_EACH_REQUEST', 'true').lower() == 'true'  # Автоматический перезапуск IIS перед каждым запросом (для учебной версии 1С)
ONEC_RESTART_COMMAND = os.getenv('ONEC_RESTART_COMMAND', 'iisreset')
ONEC_RESTART_TIMEOUT_SECONDS = int(os.getenv('ONEC_RESTART_TIMEOUT_SECONDS', '30'))
ONEC_MAX_RETRIES = int(os.getenv('ONEC_MAX_RETRIES', '3'))
ONEC_HEALTHCHECK_PATH = os.getenv('ONEC_HEALTHCHECK_PATH', '$metadata')
ONEC_HEALTH_TIMEOUT_SECONDS = int(os.getenv('ONEC_HEALTH_TIMEOUT_SECONDS', '45'))
ONEC_HEALTHCHECK_TIMEOUT_SECONDS = int(os.getenv('ONEC_HEALTHCHECK_TIMEOUT_SECONDS', '10'))
ONEC_HEALTHCHECK_INTERVAL_SECONDS = float(os.getenv('ONEC_HEALTHCHECK_INTERVAL_SECONDS', '2'))
ONEC_ORGANIZATION_KEY = os.getenv('ONEC_ORGANIZATION_KEY', '')
ONEC_PAYMENT_INVOICE_FIELD = os.getenv('ONEC_PAYMENT_INVOICE_FIELD', 'Счет_Key')
ONEC_STATUS_UNPAID_VALUE = os.getenv('ONEC_STATUS_UNPAID_VALUE', 'НеОплачен')
ONEC_STATUS_PAID_VALUE = os.getenv('ONEC_STATUS_PAID_VALUE', 'Оплачен')
ONEC_DEFAULT_CUSTOMER_TYPE = os.getenv('ONEC_DEFAULT_CUSTOMER_TYPE', 'crm')
ONEC_DEFAULT_PAYMENT_METHOD = os.getenv('ONEC_DEFAULT_PAYMENT_METHOD', 'yookassa')
ONEC_SERVICE_UNIT = os.getenv('ONEC_SERVICE_UNIT', 'шт')
ONEC_SERVICE_ACTIVITY = os.getenv('ONEC_SERVICE_ACTIVITY', 'Активна')
ONEC_AUTO_POST_DOCUMENTS = os.getenv('ONEC_AUTO_POST_DOCUMENTS', 'false').lower() == 'true'
ONEC_POSTING_MODE_OPERATIONAL = os.getenv('ONEC_POSTING_MODE_OPERATIONAL', 'false').lower() == 'true'
INVOICE_RETRY_WORKER_INTERVAL_SECONDS = int(os.getenv('INVOICE_RETRY_WORKER_INTERVAL_SECONDS', '30'))



# Настройка платежного провайдера
PAYMENT_VARIANTS = {
    'yookassa': ('django_payments_yookassa.YooKassaProvider', {
        'shop_id': YOOKASSA_SHOP_ID,
        'secret_key': YOOKASSA_SECRET_KEY,
        'capture': True,          
        'use_webhook': True,      
        'test_mode': True,            
    }),
}   

DEBUG = True
_public_payments_host = (
    PUBLIC_PAYMENTS_BASE_URL
    .replace('https://', '')
    .replace('http://', '')
    .rstrip('/')
)
_extra_allowed_hosts = [
    host.strip()
    for host in os.getenv('PAYMENTS_ALLOWED_HOSTS', '').split(',')
    if host.strip()
]
ALLOWED_HOSTS = [
    'localhost', '127.0.0.1', '0.0.0.0',
    'marketing', 'api-gateway', 'user-service', 'contact-service', 'calendar', 'documents', 'payments',
    _public_payments_host,
    *_extra_allowed_hosts,
]

DJANGO_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

THIRD_PARTY_APPS = [
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'django_filters',  # ← 
]
 

_extra_csrf_trusted_origins = [
    origin.strip()
    for origin in os.getenv('PAYMENTS_CSRF_TRUSTED_ORIGINS', '').split(',')
    if origin.strip()
]
CSRF_TRUSTED_ORIGINS = [PUBLIC_PAYMENTS_BASE_URL, *_extra_csrf_trusted_origins]


LOCAL_APPS = ['apps.yookassa_integration']

INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS
# settings.py
AUTH_USER_MODEL = 'auth.User'  # 'app_name.ModelName'


MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'databases' / 'yookassa_integration.db',  # ← contact.db
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTStatelessUserAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}



SIMPLE_JWT = {
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,       # используем тот же SECRET_KEY, что и в user-service
    'AUTH_HEADER_TYPES': ('Bearer',),
    # при необходимости можно явно задать USER_ID_CLAIM или другие опции
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    }


CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
# email
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'localhost')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '25'))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'false').lower() == 'true'
# settings.py
 
 
STATIC_URL = 'static/'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'