# Generated by Django 5.2.7 on 2026-02-06 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.PositiveIntegerField(verbose_name='ID клиента')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Оригинальное имя файла')),
                ('object_name', models.CharField(max_length=512, unique=True, verbose_name='Имя объекта в MinIO')),
                ('content_type', models.CharField(blank=True, max_length=100, verbose_name='MIME-тип')),
                ('file_size', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Размер файла (байт)')),
                ('uploaded_by', models.PositiveIntegerField(verbose_name='ID менеджера, загрузившего')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
            ],
            options={
                'verbose_name': 'Документ клиента',
                'verbose_name_plural': 'Документы клиентов',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['client_id'], name='documents_c_client__1010fe_idx'), models.Index(fields=['uploaded_at'], name='documents_c_uploade_44700f_idx')],
            },
        ),
    ]
