# Generated by Django 5.2.5 on 2025-12-20 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('task_type', models.CharField(choices=[('meeting', 'Встреча'), ('task', 'Задача'), ('reminder', 'Напоминание'), ('deadline', 'Дедлайн')], default='task', max_length=20, verbose_name='Тип задачи')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Время')),
                ('priority', models.CharField(choices=[('high', 'Высокий'), ('medium', 'Средний'), ('low', 'Низкий')], default='medium', max_length=10, verbose_name='Приоритет')),
                ('completed', models.BooleanField(default=False, verbose_name='Выполнено')),
                ('manager_id', models.IntegerField(verbose_name='ID менеджера')),
                ('manager_name', models.CharField(blank=True, max_length=255, verbose_name='Имя менеджера')),
                ('manager_email', models.EmailField(max_length=254, verbose_name='Email менеджера')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Место')),
                ('color', models.CharField(default='#4CAF50', max_length=7, verbose_name='Цвет')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='Повторяющаяся')),
                ('recurrence_rule', models.CharField(blank=True, max_length=100, verbose_name='Правило повторения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Задача календаря',
                'verbose_name_plural': 'Задачи календаря',
                'ordering': ['date', 'time'],
                'indexes': [models.Index(fields=['manager_id', 'date'], name='calendarUse_manager_8ae55b_idx'), models.Index(fields=['manager_id', 'completed'], name='calendarUse_manager_bed594_idx'), models.Index(fields=['date', 'priority'], name='calendarUse_date_2f3286_idx')],
            },
        ),
    ]
