# Generated by Django 5.2.5 on 2025-12-20 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarUser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendartask',
            name='manager_email',
        ),
        migrations.RemoveField(
            model_name='calendartask',
            name='manager_name',
        ),
    ]
