# Generated by Django 5.2.7 on 2026-03-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarUser', '0002_remove_calendartask_manager_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleCalendarCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_id', models.IntegerField(db_index=True, unique=True, verbose_name='ID менеджера')),
                ('access_token', models.TextField(blank=True)),
                ('refresh_token', models.TextField(blank=True)),
                ('token_expiry', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Google Calendar токены',
                'verbose_name_plural': 'Google Calendar токены',
            },
        ),
    ]
