# Generated by Django 5.2.5 on 2025-12-25 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название шаблона')),
                ('template_types', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], default='email', max_length=10)),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='Тема')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('sms_content', models.CharField(blank=True, max_length=500, verbose_name='Текст SMS')),
                ('variables', models.JSONField(default=list, verbose_name='Доступные переменные')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('manager_id', models.IntegerField(verbose_name='ID менеджера')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название кампании')),
                ('campaign_type', models.CharField(choices=[('individual', 'Индивидуальная'), ('bulk', 'Массовая')], default='individual', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('sending', 'Отправляется'), ('sent', 'Отправлено'), ('failed', 'Ошибка')], default='draft', max_length=20)),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='Тема')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('recipients', models.JSONField(default=list, verbose_name='ID получателей')),
                ('recipient_count', models.IntegerField(default=0, verbose_name='Количество получателей')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Время отправки')),
                ('success_count', models.IntegerField(default=0, verbose_name='Успешно отправлено')),
                ('failed_count', models.IntegerField(default=0, verbose_name='Не отправлено')),
                ('manager_id', models.IntegerField(verbose_name='ID менеджера')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='marketing.template', verbose_name='Шаблон')),
            ],
            options={
                'ordering': ['-created_at', '-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_id', models.IntegerField(verbose_name='ID получателя')),
                ('recipient_email', models.EmailField(blank=True, max_length=254, verbose_name='Email получателя')),
                ('recipient_phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон получателя')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('sent', 'Отправлено'), ('delivered', 'Доставлено'), ('opened', 'Открыто'), ('failed', 'Ошибка')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, verbose_name='Сообщение об ошибке')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_recipients', to='marketing.campaign')),
            ],
            options={
                'indexes': [models.Index(fields=['campaign', 'status'], name='marketing_c_campaig_5ad1f9_idx'), models.Index(fields=['recipient_id'], name='marketing_c_recipie_c2f532_idx')],
                'unique_together': {('campaign', 'recipient_id')},
            },
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['manager_id', 'status'], name='marketing_c_manager_6cb5c0_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['-sent_at'], name='marketing_c_sent_at_53a872_idx'),
        ),
    ]
