# Generated by Django 5.2.5 on 2025-12-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='template',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='template',
            old_name='template_types',
            new_name='template_type',
        ),
        migrations.AddIndex(
            model_name='template',
            index=models.Index(fields=['manager_id', 'template_type'], name='marketing_t_manager_7c1f64_idx'),
        ),
    ]
