# Generated by Django 5.2.7 on 2026-04-18 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('trigger_type', models.CharField(choices=[('manual', 'Manual launch'), ('user_created', 'User created'), ('deal_status_changed', 'Deal status changed')], default='manual', max_length=64)),
                ('graph', models.JSONField(blank=True, default=dict)),
                ('created_by_id', models.IntegerField(blank=True, null=True)),
                ('created_by_email', models.CharField(blank=True, default='', max_length=255)),
                ('created_by_name', models.CharField(blank=True, default='', max_length=255)),
                ('created_by_role', models.CharField(blank=True, default='', max_length=64)),
                ('updated_by_id', models.IntegerField(blank=True, null=True)),
                ('updated_by_email', models.CharField(blank=True, default='', max_length=255)),
                ('updated_by_name', models.CharField(blank=True, default='', max_length=255)),
                ('updated_by_role', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=64)),
                ('source', models.CharField(blank=True, default='', max_length=128)),
                ('trigger_payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='success', max_length=32)),
                ('logs', models.JSONField(blank=True, default=list)),
                ('error_text', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='work_process.workflow')),
            ],
            options={
                'ordering': ['-started_at', '-id'],
            },
        ),
    ]
