# Generated by Django 5.2.7 on 2026-04-13 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatService', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='sender_role',
            field=models.CharField(choices=[('manager', 'Manager'), ('admin', 'Admin'), ('telegram_client', 'Telegram Client')], max_length=20),
        ),
        migrations.AlterField(
            model_name='chatparticipant',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('admin', 'Admin'), ('telegram_client', 'Telegram Client')], max_length=20),
        ),
        migrations.CreateModel(
            name='TelegramRoomBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_chat_id', models.BigIntegerField(unique=True)),
                ('telegram_username', models.CharField(blank=True, max_length=255)),
                ('telegram_first_name', models.CharField(blank=True, max_length=255)),
                ('telegram_last_name', models.CharField(blank=True, max_length=255)),
                ('last_forwarded_message_id', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_binding', to='chatService.chatroom')),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
    ]
